dataset: mnist
mode: inference
layer_sizes: [784, 256, 10]
batch_size: 1
rerun: network_results/mnist/training/MLP/sync1_fnb1_2/42_ep50_b36_784_256_10_acc0.979_adam_.json

override_params:
  - batch_size

trace_event_timing: true
