dataset: mnist
mode: inference
layer_sizes: [784, 128, 128, 10]
batch_size: 1
rerun: network_results/mnist/training/MLP/sync_training/42_ep20_batch36_784_128_128_10_acc0.976_adam_.json
firing_nb: 1
sync_rate: 1

override_params:
  - batch_size
  - firing_nb
  - sync_rate

trace_event_timing: true
